[pytest]

# Custom Markers
markers =
    positive: mark a test as a positive test.
    negative: mark a test as a negative test.
    api: mark a test as an API test.
    ui: mark a test as a UI test.
    smoke: mark a test as a smoke test.
    regression: mark a test as a regression test.

addopts = --screenshot=only-on-failure --video=retain-on-failure --tracing=retain-on-failure
