[pytest]

# Custom Markers
markers =
    positive: mark a test as a positive test.
    negative: mark a test as a negative test.
    api: mark a test as an API test.
    ui: mark a test as a UI test.
    smoke: mark a test as a smoke test.
    regression: mark a test as a regression test.

# HTML Report Configuration
addopts = -vrA --tb=short --html=reports/report.html --self-contained-html --junitxml=reports/junit_results.xml

# Logging Configuration on Framework Level
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format=%Y-%m-%d %H:%M:%S